import { z } from "zod";

export const SpotifyCodeExchangeResponseSchema = z.object({
  access_token: z.string(),
  token_type: z.string(),
  expires_in: z.number(),
  refresh_token: z.string().optional(),
  scope: z.string(),
});

export type SpotifyCodeExchangeResponse = z.infer<
  typeof SpotifyCodeExchangeResponseSchema
>;

export type SpotifySongData = {
  tracks: {
    href: string;
    items: {
      album: {
        album_type: string;
        artists: {
          external_urls: {
            spotify: string;
          };
          href: string;
          id: string;
          name: string;
          type: string;
          uri: string;
        }[];
        available_markets: string[];
        external_urls: {
          spotify: string;
        };
        href: string;
        id: string;
        images: {
          height: number;
          url: string;
          width: number;
        }[];
        name: string;
        release_date: string;
        release_date_precision: string;
        total_tracks: number;
        type: string;
        uri: string;
      };
      artists: {
        external_urls: {
          spotify: string;
        };
        href: string;
        id: string;
        name: string;
        type: string;
        uri: string;
      }[];
      available_markets?: string[];
      disc_number: number;
      duration_ms: number;
      explicit: boolean;
      external_ids: {
        isrc: string;
      };
      external_urls: {
        spotify: string;
      };
      href: string;
      id: string;
      is_local: boolean;
      name: string;
      popularity: number;
      preview_url: string;
      track_number: number;
      type: string;
      uri: string;
    }[];

    limit: number;
    /** "https://api.spotify.com/v1/search?query=Ashnikko&type=track&locale=*&offset=15&limit=15" */
    next: string | null;
    offset: number;
    previous: string | null;
    total: number;
  };
};

export const SONG_MOCK_DATA: SpotifySongData = {
  tracks: {
    href: "https://api.spotify.com/v1/search?query=Ashnikko&type=track&locale=*&offset=0&limit=15",
    items: [
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/438ToDoVaJH5aTIXXrlDyI",
          },
          href: "https://api.spotify.com/v1/albums/438ToDoVaJH5aTIXXrlDyI",
          id: "438ToDoVaJH5aTIXXrlDyI",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27311b63834a1a557cc77403458",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0211b63834a1a557cc77403458",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485111b63834a1a557cc77403458",
              width: 64,
            },
          ],
          name: "DEMIDEVIL",
          release_date: "2021-01-15",
          release_date_precision: "day",
          total_tracks: 10,
          type: "album",
          uri: "spotify:album:438ToDoVaJH5aTIXXrlDyI",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/053q0ukIDRgzwTr4vNSwab",
            },
            href: "https://api.spotify.com/v1/artists/053q0ukIDRgzwTr4vNSwab",
            id: "053q0ukIDRgzwTr4vNSwab",
            name: "Grimes",
            type: "artist",
            uri: "spotify:artist:053q0ukIDRgzwTr4vNSwab",
          },
        ],
        disc_number: 1,
        duration_ms: 126663,
        explicit: true,
        external_ids: { isrc: "GBAYE2000452" },
        external_urls: {
          spotify: "https://open.spotify.com/track/1jR9XTpUeT6a82Yz4GNCCo",
        },
        href: "https://api.spotify.com/v1/tracks/1jR9XTpUeT6a82Yz4GNCCo",
        id: "1jR9XTpUeT6a82Yz4GNCCo",
        is_local: false,
        name: "Cry (feat. Grimes)",
        popularity: 60,
        preview_url:
          "https://p.scdn.co/mp3-preview/706376638150bab0363eaafbfc9937f5e7cc1b2a?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 7,
        type: "track",
        uri: "spotify:track:1jR9XTpUeT6a82Yz4GNCCo",
      },
      {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5eKuModdAdZRmc51241r4D",
          },
          href: "https://api.spotify.com/v1/albums/5eKuModdAdZRmc51241r4D",
          id: "5eKuModdAdZRmc51241r4D",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b2734d165570efefd46cfad3eb36",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e024d165570efefd46cfad3eb36",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d000048514d165570efefd46cfad3eb36",
              width: 64,
            },
          ],
          name: "Hi, It's Me",
          release_date: "2019-07-12",
          release_date_precision: "day",
          total_tracks: 5,
          type: "album",
          uri: "spotify:album:5eKuModdAdZRmc51241r4D",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3IJ21966TwNZI24MwZHMu4",
            },
            href: "https://api.spotify.com/v1/artists/3IJ21966TwNZI24MwZHMu4",
            id: "3IJ21966TwNZI24MwZHMu4",
            name: "Baby Tate",
            type: "artist",
            uri: "spotify:artist:3IJ21966TwNZI24MwZHMu4",
          },
        ],
        disc_number: 1,
        duration_ms: 167317,
        explicit: true,
        external_ids: { isrc: "GBAYE1900593" },
        external_urls: {
          spotify: "https://open.spotify.com/track/6qNB2ChCVPepl5ZjVJJTUW",
        },
        href: "https://api.spotify.com/v1/tracks/6qNB2ChCVPepl5ZjVJJTUW",
        id: "6qNB2ChCVPepl5ZjVJJTUW",
        is_local: false,
        name: "STUPID (feat. Yung Baby Tate)",
        popularity: 66,
        preview_url:
          "https://p.scdn.co/mp3-preview/e5057988f85356e448e5493e54bbdbdd1dfbfcc4?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 3,
        type: "track",
        uri: "spotify:track:6qNB2ChCVPepl5ZjVJJTUW",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/438ToDoVaJH5aTIXXrlDyI",
          },
          href: "https://api.spotify.com/v1/albums/438ToDoVaJH5aTIXXrlDyI",
          id: "438ToDoVaJH5aTIXXrlDyI",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27311b63834a1a557cc77403458",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0211b63834a1a557cc77403458",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485111b63834a1a557cc77403458",
              width: 64,
            },
          ],
          name: "DEMIDEVIL",
          release_date: "2021-01-15",
          release_date_precision: "day",
          total_tracks: 10,
          type: "album",
          uri: "spotify:album:438ToDoVaJH5aTIXXrlDyI",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6lay1nwbE6hTx1jivysUAL",
            },
            href: "https://api.spotify.com/v1/artists/6lay1nwbE6hTx1jivysUAL",
            id: "6lay1nwbE6hTx1jivysUAL",
            name: "Princess Nokia",
            type: "artist",
            uri: "spotify:artist:6lay1nwbE6hTx1jivysUAL",
          },
        ],
        disc_number: 1,
        duration_ms: 178404,
        explicit: true,
        external_ids: { isrc: "GBAYE2000706" },
        external_urls: {
          spotify: "https://open.spotify.com/track/11ZulcYY4lowvcQm4oe3VJ",
        },
        href: "https://api.spotify.com/v1/tracks/11ZulcYY4lowvcQm4oe3VJ",
        id: "11ZulcYY4lowvcQm4oe3VJ",
        is_local: false,
        name: "Slumber Party (feat. Princess Nokia)",
        popularity: 73,
        preview_url:
          "https://p.scdn.co/mp3-preview/61a45d3d731526533d81fa2343b027f1535b4b08?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 4,
        type: "track",
        uri: "spotify:track:11ZulcYY4lowvcQm4oe3VJ",
      },
      {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5tRhwDUyr3HypAaJysxUki",
          },
          href: "https://api.spotify.com/v1/albums/5tRhwDUyr3HypAaJysxUki",
          id: "5tRhwDUyr3HypAaJysxUki",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273459032f0de5f7f188301d99b",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02459032f0de5f7f188301d99b",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851459032f0de5f7f188301d99b",
              width: 64,
            },
          ],
          name: "Daisy",
          release_date: "2020-07-09",
          release_date_precision: "day",
          total_tracks: 2,
          type: "album",
          uri: "spotify:album:5tRhwDUyr3HypAaJysxUki",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 146523,
        explicit: true,
        external_ids: { isrc: "GBAYE2000596" },
        external_urls: {
          spotify: "https://open.spotify.com/track/0AUvWawuP0ibk4SQ3sIZjk",
        },
        href: "https://api.spotify.com/v1/tracks/0AUvWawuP0ibk4SQ3sIZjk",
        id: "0AUvWawuP0ibk4SQ3sIZjk",
        is_local: false,
        name: "Daisy",
        popularity: 65,
        preview_url:
          "https://p.scdn.co/mp3-preview/8dea3bcf4bcfd432e0dd90df4f2f83e356255535?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 1,
        type: "track",
        uri: "spotify:track:0AUvWawuP0ibk4SQ3sIZjk",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/438ToDoVaJH5aTIXXrlDyI",
          },
          href: "https://api.spotify.com/v1/albums/438ToDoVaJH5aTIXXrlDyI",
          id: "438ToDoVaJH5aTIXXrlDyI",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27311b63834a1a557cc77403458",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0211b63834a1a557cc77403458",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485111b63834a1a557cc77403458",
              width: 64,
            },
          ],
          name: "DEMIDEVIL",
          release_date: "2021-01-15",
          release_date_precision: "day",
          total_tracks: 10,
          type: "album",
          uri: "spotify:album:438ToDoVaJH5aTIXXrlDyI",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0IF46mUS8NXjgHabxk2MCM",
            },
            href: "https://api.spotify.com/v1/artists/0IF46mUS8NXjgHabxk2MCM",
            id: "0IF46mUS8NXjgHabxk2MCM",
            name: "Kelis",
            type: "artist",
            uri: "spotify:artist:0IF46mUS8NXjgHabxk2MCM",
          },
        ],
        disc_number: 1,
        duration_ms: 191149,
        explicit: true,
        external_ids: { isrc: "GBAYE2000707" },
        external_urls: {
          spotify: "https://open.spotify.com/track/1S85LGnDPKKOkfuFaK6vFu",
        },
        href: "https://api.spotify.com/v1/tracks/1S85LGnDPKKOkfuFaK6vFu",
        id: "1S85LGnDPKKOkfuFaK6vFu",
        is_local: false,
        name: "Deal With It (feat. Kelis)",
        popularity: 61,
        preview_url:
          "https://p.scdn.co/mp3-preview/aab0081dfb094684c61a209cb2190b8596e90210?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 3,
        type: "track",
        uri: "spotify:track:1S85LGnDPKKOkfuFaK6vFu",
      },
      {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/1hFgxn07lR5agY6sk9fHQJ",
          },
          href: "https://api.spotify.com/v1/albums/1hFgxn07lR5agY6sk9fHQJ",
          id: "1hFgxn07lR5agY6sk9fHQJ",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273414cc2a7ceb94c9c1d5624f5",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02414cc2a7ceb94c9c1d5624f5",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851414cc2a7ceb94c9c1d5624f5",
              width: 64,
            },
          ],
          name: "You Make Me Sick!",
          release_date: "2023-02-08",
          release_date_precision: "day",
          total_tracks: 1,
          type: "album",
          uri: "spotify:album:1hFgxn07lR5agY6sk9fHQJ",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 138299,
        explicit: true,
        external_ids: { isrc: "GBAYE2300003" },
        external_urls: {
          spotify: "https://open.spotify.com/track/2cK6tRFd7PRPFY1ZwJAKeq",
        },
        href: "https://api.spotify.com/v1/tracks/2cK6tRFd7PRPFY1ZwJAKeq",
        id: "2cK6tRFd7PRPFY1ZwJAKeq",
        is_local: false,
        name: "You Make Me Sick!",
        popularity: 56,
        preview_url:
          "https://p.scdn.co/mp3-preview/8bf097c1497bd0cce8fd628b642a7de72bd6379b?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 1,
        type: "track",
        uri: "spotify:track:2cK6tRFd7PRPFY1ZwJAKeq",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4xZP0Vuf4DNK7wsp3ZKbQ0",
          },
          href: "https://api.spotify.com/v1/albums/4xZP0Vuf4DNK7wsp3ZKbQ0",
          id: "4xZP0Vuf4DNK7wsp3ZKbQ0",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27358c2d19eb1d382296bad3911",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0258c2d19eb1d382296bad3911",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485158c2d19eb1d382296bad3911",
              width: 64,
            },
          ],
          name: "WEEDKILLER",
          release_date: "2023-08-25",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:4xZP0Vuf4DNK7wsp3ZKbQ0",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 132818,
        explicit: true,
        external_ids: { isrc: "GBAYE2300007" },
        external_urls: {
          spotify: "https://open.spotify.com/track/150oCxP7slbU48qYS8ez78",
        },
        href: "https://api.spotify.com/v1/tracks/150oCxP7slbU48qYS8ez78",
        id: "150oCxP7slbU48qYS8ez78",
        is_local: false,
        name: "Cheerleader",
        popularity: 60,
        preview_url:
          "https://p.scdn.co/mp3-preview/c84f928f3d94452767d861b1b2e5f79ad6f77f37?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 6,
        type: "track",
        uri: "spotify:track:150oCxP7slbU48qYS8ez78",
      },
      {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5IRp7hBdLQOz5gB90M1hg0",
          },
          href: "https://api.spotify.com/v1/albums/5IRp7hBdLQOz5gB90M1hg0",
          id: "5IRp7hBdLQOz5gB90M1hg0",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b2739ee25a36c6fe0c2841fff542",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e029ee25a36c6fe0c2841fff542",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d000048519ee25a36c6fe0c2841fff542",
              width: 64,
            },
          ],
          name: "Tantrum",
          release_date: "2020-03-06",
          release_date_precision: "day",
          total_tracks: 1,
          type: "album",
          uri: "spotify:album:5IRp7hBdLQOz5gB90M1hg0",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 140010,
        explicit: true,
        external_ids: { isrc: "GBAYE2000094" },
        external_urls: {
          spotify: "https://open.spotify.com/track/3htJKHlAjUoRmNLheJ8uTV",
        },
        href: "https://api.spotify.com/v1/tracks/3htJKHlAjUoRmNLheJ8uTV",
        id: "3htJKHlAjUoRmNLheJ8uTV",
        is_local: false,
        name: "Tantrum",
        popularity: 61,
        preview_url:
          "https://p.scdn.co/mp3-preview/8ef62000de259482263783404f4e86a4c57c3485?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 1,
        type: "track",
        uri: "spotify:track:3htJKHlAjUoRmNLheJ8uTV",
      },
      {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/2AWdSvqkBNvj9eeM48KQTJ",
          },
          href: "https://api.spotify.com/v1/albums/2AWdSvqkBNvj9eeM48KQTJ",
          id: "2AWdSvqkBNvj9eeM48KQTJ",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273c41af63dd888032c52715215",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02c41af63dd888032c52715215",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851c41af63dd888032c52715215",
              width: 64,
            },
          ],
          name: "Halloweenie IV: Innards",
          release_date: "2021-10-22",
          release_date_precision: "day",
          total_tracks: 1,
          type: "album",
          uri: "spotify:album:2AWdSvqkBNvj9eeM48KQTJ",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 170646,
        explicit: false,
        external_ids: { isrc: "GBAYE2101376" },
        external_urls: {
          spotify: "https://open.spotify.com/track/2hwUHHqLSEue41V952MtD2",
        },
        href: "https://api.spotify.com/v1/tracks/2hwUHHqLSEue41V952MtD2",
        id: "2hwUHHqLSEue41V952MtD2",
        is_local: false,
        name: "Halloweenie IV: Innards",
        popularity: 56,
        preview_url:
          "https://p.scdn.co/mp3-preview/d84b91f14b264c7d56bf27b751e884f4ccd87615?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 1,
        type: "track",
        uri: "spotify:track:2hwUHHqLSEue41V952MtD2",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4xZP0Vuf4DNK7wsp3ZKbQ0",
          },
          href: "https://api.spotify.com/v1/albums/4xZP0Vuf4DNK7wsp3ZKbQ0",
          id: "4xZP0Vuf4DNK7wsp3ZKbQ0",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27358c2d19eb1d382296bad3911",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0258c2d19eb1d382296bad3911",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485158c2d19eb1d382296bad3911",
              width: 64,
            },
          ],
          name: "WEEDKILLER",
          release_date: "2023-08-25",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:4xZP0Vuf4DNK7wsp3ZKbQ0",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0avMDS4HyoCEP6RqZJWpY2",
            },
            href: "https://api.spotify.com/v1/artists/0avMDS4HyoCEP6RqZJWpY2",
            id: "0avMDS4HyoCEP6RqZJWpY2",
            name: "Ethel Cain",
            type: "artist",
            uri: "spotify:artist:0avMDS4HyoCEP6RqZJWpY2",
          },
        ],
        disc_number: 1,
        duration_ms: 255875,
        explicit: false,
        external_ids: { isrc: "GBAYE2301191" },
        external_urls: {
          spotify: "https://open.spotify.com/track/55owCz7823hXvvTm3apoZ9",
        },
        href: "https://api.spotify.com/v1/tracks/55owCz7823hXvvTm3apoZ9",
        id: "55owCz7823hXvvTm3apoZ9",
        is_local: false,
        name: "Dying Star (feat. Ethel Cain)",
        popularity: 54,
        preview_url:
          "https://p.scdn.co/mp3-preview/0c4e105bbe9b045246e5b768f70e7fadd824969c?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 13,
        type: "track",
        uri: "spotify:track:55owCz7823hXvvTm3apoZ9",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "BY",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/438ToDoVaJH5aTIXXrlDyI",
          },
          href: "https://api.spotify.com/v1/albums/438ToDoVaJH5aTIXXrlDyI",
          id: "438ToDoVaJH5aTIXXrlDyI",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27311b63834a1a557cc77403458",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0211b63834a1a557cc77403458",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485111b63834a1a557cc77403458",
              width: 64,
            },
          ],
          name: "DEMIDEVIL",
          release_date: "2021-01-15",
          release_date_precision: "day",
          total_tracks: 10,
          type: "album",
          uri: "spotify:album:438ToDoVaJH5aTIXXrlDyI",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 146523,
        explicit: true,
        external_ids: { isrc: "GBAYE2000596" },
        external_urls: {
          spotify: "https://open.spotify.com/track/2g1KggY9PKvsoEAOaiz4xx",
        },
        href: "https://api.spotify.com/v1/tracks/2g1KggY9PKvsoEAOaiz4xx",
        id: "2g1KggY9PKvsoEAOaiz4xx",
        is_local: false,
        name: "Daisy",
        popularity: 71,
        preview_url:
          "https://p.scdn.co/mp3-preview/8dea3bcf4bcfd432e0dd90df4f2f83e356255535?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 1,
        type: "track",
        uri: "spotify:track:2g1KggY9PKvsoEAOaiz4xx",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4xZP0Vuf4DNK7wsp3ZKbQ0",
          },
          href: "https://api.spotify.com/v1/albums/4xZP0Vuf4DNK7wsp3ZKbQ0",
          id: "4xZP0Vuf4DNK7wsp3ZKbQ0",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27358c2d19eb1d382296bad3911",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0258c2d19eb1d382296bad3911",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485158c2d19eb1d382296bad3911",
              width: 64,
            },
          ],
          name: "WEEDKILLER",
          release_date: "2023-08-25",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:4xZP0Vuf4DNK7wsp3ZKbQ0",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 152207,
        explicit: true,
        external_ids: { isrc: "GBAYE2301187" },
        external_urls: {
          spotify: "https://open.spotify.com/track/3u47ne7GE7PoMXvzRa16s1",
        },
        href: "https://api.spotify.com/v1/tracks/3u47ne7GE7PoMXvzRa16s1",
        id: "3u47ne7GE7PoMXvzRa16s1",
        is_local: false,
        name: "Moonlight Magic",
        popularity: 56,
        preview_url:
          "https://p.scdn.co/mp3-preview/84fd5bb7877d9b8ab7b610baf5e953d89e783a78?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 7,
        type: "track",
        uri: "spotify:track:3u47ne7GE7PoMXvzRa16s1",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4xZP0Vuf4DNK7wsp3ZKbQ0",
          },
          href: "https://api.spotify.com/v1/albums/4xZP0Vuf4DNK7wsp3ZKbQ0",
          id: "4xZP0Vuf4DNK7wsp3ZKbQ0",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27358c2d19eb1d382296bad3911",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0258c2d19eb1d382296bad3911",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485158c2d19eb1d382296bad3911",
              width: 64,
            },
          ],
          name: "WEEDKILLER",
          release_date: "2023-08-25",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:4xZP0Vuf4DNK7wsp3ZKbQ0",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 138299,
        explicit: true,
        external_ids: { isrc: "GBAYE2300003" },
        external_urls: {
          spotify: "https://open.spotify.com/track/7iR1y5YfpmJ6ME8zkKnlQj",
        },
        href: "https://api.spotify.com/v1/tracks/7iR1y5YfpmJ6ME8zkKnlQj",
        id: "7iR1y5YfpmJ6ME8zkKnlQj",
        is_local: false,
        name: "You Make Me Sick!",
        popularity: 58,
        preview_url:
          "https://p.scdn.co/mp3-preview/8bf097c1497bd0cce8fd628b642a7de72bd6379b?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 2,
        type: "track",
        uri: "spotify:track:7iR1y5YfpmJ6ME8zkKnlQj",
      },
      {
        album: {
          album_type: "single",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/76o6AaSFr2owQN4AEit99z",
          },
          href: "https://api.spotify.com/v1/albums/76o6AaSFr2owQN4AEit99z",
          id: "76o6AaSFr2owQN4AEit99z",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b273e1832a6dbfeadb0cc72c99bb",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e02e1832a6dbfeadb0cc72c99bb",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d00004851e1832a6dbfeadb0cc72c99bb",
              width: 64,
            },
          ],
          name: "Halloweenie V: The Moss King",
          release_date: "2023-10-27",
          release_date_precision: "day",
          total_tracks: 1,
          type: "album",
          uri: "spotify:album:76o6AaSFr2owQN4AEit99z",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 127439,
        explicit: true,
        external_ids: { isrc: "GBAYE2301757" },
        external_urls: {
          spotify: "https://open.spotify.com/track/0MWkCSW0W7rGLSvDR2xExC",
        },
        href: "https://api.spotify.com/v1/tracks/0MWkCSW0W7rGLSvDR2xExC",
        id: "0MWkCSW0W7rGLSvDR2xExC",
        is_local: false,
        name: "Halloweenie V: The Moss King",
        popularity: 52,
        preview_url:
          "https://p.scdn.co/mp3-preview/cb9462cf1ead5805c7d848763d220d191842a270?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 1,
        type: "track",
        uri: "spotify:track:0MWkCSW0W7rGLSvDR2xExC",
      },
      {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
              },
              href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
              id: "3PyJHH2wyfQK3WZrk9rpmP",
              name: "Ashnikko",
              type: "artist",
              uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
            },
          ],
          available_markets: [
            "AR",
            "AU",
            "AT",
            "BE",
            "BO",
            "BR",
            "BG",
            "CA",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DK",
            "DO",
            "DE",
            "EC",
            "EE",
            "SV",
            "FI",
            "FR",
            "GR",
            "GT",
            "HN",
            "HK",
            "HU",
            "IS",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MY",
            "MT",
            "MX",
            "NL",
            "NZ",
            "NI",
            "NO",
            "PA",
            "PY",
            "PE",
            "PH",
            "PL",
            "PT",
            "SG",
            "SK",
            "ES",
            "SE",
            "CH",
            "TW",
            "TR",
            "UY",
            "US",
            "GB",
            "AD",
            "LI",
            "MC",
            "ID",
            "JP",
            "TH",
            "VN",
            "RO",
            "IL",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KZ",
            "MD",
            "UA",
            "AL",
            "BA",
            "HR",
            "ME",
            "MK",
            "RS",
            "SI",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "AM",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GE",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "PR",
            "WS",
            "SM",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "KG",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "UZ",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "TJ",
            "VE",
            "ET",
            "XK",
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4xZP0Vuf4DNK7wsp3ZKbQ0",
          },
          href: "https://api.spotify.com/v1/albums/4xZP0Vuf4DNK7wsp3ZKbQ0",
          id: "4xZP0Vuf4DNK7wsp3ZKbQ0",
          images: [
            {
              height: 640,
              url: "https://i.scdn.co/image/ab67616d0000b27358c2d19eb1d382296bad3911",
              width: 640,
            },
            {
              height: 300,
              url: "https://i.scdn.co/image/ab67616d00001e0258c2d19eb1d382296bad3911",
              width: 300,
            },
            {
              height: 64,
              url: "https://i.scdn.co/image/ab67616d0000485158c2d19eb1d382296bad3911",
              width: 64,
            },
          ],
          name: "WEEDKILLER",
          release_date: "2023-08-25",
          release_date_precision: "day",
          total_tracks: 13,
          type: "album",
          uri: "spotify:album:4xZP0Vuf4DNK7wsp3ZKbQ0",
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3PyJHH2wyfQK3WZrk9rpmP",
            },
            href: "https://api.spotify.com/v1/artists/3PyJHH2wyfQK3WZrk9rpmP",
            id: "3PyJHH2wyfQK3WZrk9rpmP",
            name: "Ashnikko",
            type: "artist",
            uri: "spotify:artist:3PyJHH2wyfQK3WZrk9rpmP",
          },
        ],
        disc_number: 1,
        duration_ms: 148690,
        explicit: true,
        external_ids: { isrc: "GBAYE2300004" },
        external_urls: {
          spotify: "https://open.spotify.com/track/3nBX9Z0kQwUrtnbLFnw0xk",
        },
        href: "https://api.spotify.com/v1/tracks/3nBX9Z0kQwUrtnbLFnw0xk",
        id: "3nBX9Z0kQwUrtnbLFnw0xk",
        is_local: false,
        name: "Worms",
        popularity: 62,
        preview_url:
          "https://p.scdn.co/mp3-preview/f3d032df1f7ccd3ed1e90437b7dd165d3525d4f5?cid=96145fd07a8b4c059bea3381ca3dae28",
        track_number: 3,
        type: "track",
        uri: "spotify:track:3nBX9Z0kQwUrtnbLFnw0xk",
      },
    ],
    limit: 15,
    next: "https://api.spotify.com/v1/search?query=Ashnikko&type=track&locale=*&offset=15&limit=15",
    offset: 0,
    previous: null,
    total: 352,
  },
};
